#!/bin/bash

echo "🔍 FIREBASE CONSOLE VERIFICATION CHECKLIST"
echo "==========================================="
echo ""
echo "📋 CRITICAL STEPS TO VERIFY IN FIREBASE CONSOLE:"
echo ""
echo "1. 🌐 Go to: https://console.firebase.google.com/project/studio-5461927014-a4c9a"
echo ""
echo "2. 🔐 Navigate to Authentication → Sign-in method:"
echo "   ✅ Google provider: ENABLED"
echo "   ✅ Email/Password provider: ENABLED" 
echo ""
echo "3. 🌍 Check Authentication → Settings → Authorized domains:"
echo "   ✅ localhost"
echo "   ✅ studio-5461927014-a4c9a.firebaseapp.com"
echo "   ✅ 9000-firebase-studio-[...].cluster-kadnvepafzbgiwrf2a46powzly.cloudworkstations.dev"
echo "   ✅ Any other domains where your app is hosted"
echo ""
echo "4. 🔧 Verify Project Settings → General:"
echo "   ✅ Project ID: studio-5461927014-a4c9a"
echo "   ✅ Web API Key exists"
echo ""
echo "5. 📱 If using OAuth consent screen (Google Cloud Console):"
echo "   → https://console.cloud.google.com/apis/credentials/consent"
echo "   ✅ App name configured"
echo "   ✅ Support email set"
echo "   ✅ Authorized domains added"
echo ""
echo "⚠️  MOST COMMON ISSUE: Authorized domains not configured correctly"
echo "   Add your exact Firebase Studio URL to authorized domains!"
echo ""
